defaults:
  - _self_
  - data: egodorsalpose
  - model: deltadorsalpose
  - callbacks: default
  - logger: wandb
  - paths: default
  - hydra: default

  - experiment: null

  - hparams_search: null

  - debug: null

callbacks:
  model_checkpoint:
    monitor: "val/mpjpe"
  early_stopping:
    monitor: "val/mpjpe"


task_name: "egodorsalpose"

tags: ["pose"]

min_epochs: 1
max_epochs: 10

train: True

test: True

ckpt_path: null

seed: null
