# @package _global_

# default debugging setup, runs 1 full epoch
# other debugging configs can inherit from this one

# overwrite task name so debugging logs are stored in separate folder
task_name: "debug"
max_epochs: 2

# disable callbacks and loggers during debugging
callbacks: null

logger:
  wandb:
    offline: true

# sets level of all command line loggers to 'DEBUG'
# https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
hydra:
  job_logging:
    root:
      level: DEBUG

  # use this to also set hydra loggers to 'DEBUG'
  # verbose: True

data:
  sample_ratio: .001
  num_workers: 0 # debuggers don't like multiprocessing
  pin_memory: False # disable gpu memory pin
